### ISSUE TITLE
unmatched arch

### ISSUE THREAD

**Issue by anjandev** [toluschr/xdeb#2]
Certain packages like the [brother generic driver](https://support.brother.com/g/b/downloadlist.aspx?c=eu_ot&lang=en&prod=mfcl2700dw_us_eu_as&os=128) only has an i386 version . As such, when I try making a package from it, I get the following error:

```
[+] Created Package
index: ignoring mfcl2700dwcupswrapper-3.2.0_1, unmatched arch (i386)
index: ignoring mfcl2700dwlpr-3.2.0_1, unmatched arch (i386)
index: 0 packages registered.
```
When you install the package on a 64 bit debian based computer, brother tells you to use the `--force` option with dpkg to ignore this mismatch of archs ([source](https://support.brother.com/g/b/downloadhowto.aspx?c=eu_ot&lang=en&prod=mfcl2700dw_us_eu_as&os=128&dlid=dlf101791_000&flang=4&type3=559)). Indeed, even after ignoring this mismatch of archs, the program works provided you have the correct multilib dependencies installed (see installation instructions from brother for the dependencies). I just installed `dpkg` on void and used brother's instructions. I understand how dangerous that is but I spent alot of time trying to fix it the proper way. The ideal solution would be having an option to ignore mismatching archs.

This program is great because it allows us to archive older programs that only have a .deb. However, alot of these older .deb programs only work with i386. As such it is wise to add this option.

**Comment by toluschr** [comment]
I would just add another option (`--arch`) to manually set the arch, as the official multilib repository adds a `-32bit` suffix and does the same.

Tell me if you are ok with this change.

**Comment by anjandev** [comment]
Ya, that sounds great! I'll be happy to test this change.

Thanks
