### ISSUE TITLE
[BUG] Mysql Workbench Community

### ISSUE THREAD

**Issue by ebiscaia** [toluschr/xdeb#23]
I am trying to convert mysql workbench community with xdeb which I downloaded today and managed to install brave.

The output of the command is:
```
xdeb mysql-workbench-community_8.0.33-1ubuntu23.04_amd64.deb 
tar: /home/eddie/Downloads/mysql/control.tar.?z: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
[-] Not a valid deb file
```

A further inspection show that the files inside are compressed with zst and I was able to extract the files by:
```
tar --use-compress-program=unzstd -xvf data.tar.zst
```
So I think it would be just a matter of updating the list of compressed file formats.

Thanks,

**Comment by toluschr** [comment]
Sorry for the delayed reply, this was already fixed by https://github.com/toluschr/xdeb/commit/e3a6d0d468741e48a23e8b2f4b94aef10e982a89. It's probably time for a new release.
