### ISSUE TITLE
Error "Dependency 'ar' not found"

### ISSUE THREAD

**Issue by Bespalov-AV** [toluschr/xdeb#3]
Hi!
I try to convert a deb package and i get error.
`[archer@void scripts]$ ./xdeb ./yandex-disk_latest_amd64.deb 
[!] Dependency 'ar' not found
`
How can I fix it?

**Comment by toluschr** [comment]
Weird. Usually ar should already be preinstalled on your system. Make sure you have the package `binutils` installed. (`xlocate '^/usr/bin/ar$'`)

**Comment by Bespalov-AV** [comment]
Thank you!
binutils was not installed. I did not know which package contains 'ar'.
