### ISSUE TITLE
MISSING: alsa-lib-1.0.20_1 (  Version 1.2.3.2_1 in repositories)

### ISSUE THREAD

**Issue by gorkawien** [toluschr/xdeb#5]
MISSING: alsa-lib-1.0.20_1
Transaction aborted due to unresolved dependencies.
The version in void linux repositories is  1.2.3.2_1

**Comment by toluschr** [comment]
Thanks for reporting this. It seems that the repository got out of sync. When I tested the script, the issue didn't occur.

**Comment by gorkawien** [comment]
Thanks for the fast answer. I really appreciate it!!
You are doing an amazing job!!
