### ISSUE TITLE
Error (not a valid deb file)

### ISSUE THREAD

**Issue by mike-of-earth** [toluschr/xdeb#7]
# Information
I could be the package, but I've downloaded it 3 times and it still bombs. Made sure I was using the latest posted xdeb, not from the master. Deb file is softmaker-office-2021_1022-01_amd64

* options:<br>
  *output of* `env | grep XDEB`  - blank. I am running it from the usr/local/bin.
* version:<br>
  *either version, or commit id. ie: [9f69cf3, 1.2]* release 4 
* cmdline:<br>
  *command used to convert the package, including* # ./xdeb -Sde softmaker-office-2021_1022-01_amd64.deb
* [ X] build failed
* [ ] installation failed

# Package 

* name:<br>
 softmaker-office-2021_1022-01_amd64.deb
* download:<br>
https://www.softmaker.com/en/softmaker-office-download

# Script output
[+] Synced shlibs
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[-] Not a valid deb file

# ./xdeb -Sde softmaker-office-2021_1022-01_amd64.deb
[+] Synced shlibs
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[-] Not a valid deb file
# 

# Describe the issue
The .deb file is in the /usrlocal/bin directory with xdeb. I installed all the listed xdeb dependencies. I did not set the xdeb pkgroot option, as it read like it was optional. This may very well be an error on my part... just thought this was the best place to get help.
TIA!

**Comment by toluschr** [comment]
`xbps-install xz`. I'll add it to the dependencies.
Try not to have the deb package in `/usr/local/bin`, but in a directory your user has write access to, like `~/downloads`

**Comment by mike-of-earth** [comment]
That works! Awesome utility, thanks for all your hard work!
